### ISSUE TITLE
Output of first command not used if second command exits non-zero

### ISSUE THREAD

**Issue by HaleTom** [scrooloose/syntastic#1897]
```
Syntastic version: 3.7.0-226 (Vim 704, Linux, GUI)                                                                                                                                                    
Info for filetype: ruby                                                                                                                                                                               
Global mode: active                                                                                                                                                                                   
Filetype ruby is active                                                                                                                                                                               
The current file will be checked automatically                                                                                                                                                        
Available checkers: mri rubocop                                                                                                                                                                       
Currently enabled checkers: mri rubocop
```

I was wondering why with both `mri` and `rubocop` I was getting a null location list even with a file with purposefully broken syntax.

It seems that if `rubocop` returns non-zero (it returned 2 with my `.rubocop.yml` config file issue), the `mri` output already obtained (it's first in the list) is discarded.

Here is some config which will make `rubocop` spit the dummy:
```
Style/TrailingComma:
  Description: Checks for trailing comma in parameter lists and literals.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas
  Enabled: false
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
  - comma
  - no_comma
Style/TrivialAccessors:
```
